<group name="b/manipulator">
        <chain base_link="b/base_link" tip_link="b/tool0" />
    </group>
    <group name="b/endeffector">
        <link name="b/tool0" />
    </group>
    <!--GROUP STATES: Purpose: Define a named state for a particular group, in terms of joint values. This is useful to define states like 'folded arms'-->
    <group_state name="home" group="b/manipulator">
        <joint name="b/elbow_joint" value="0" />
        <joint name="b/shoulder_lift_joint" value="0" />
        <joint name="b/shoulder_pan_joint" value="0" />
        <joint name="b/wrist_1_joint" value="0" />
        <joint name="b/wrist_2_joint" value="0" />
        <joint name="b/wrist_3_joint" value="0" />
    </group_state>
    <group_state name="up" group="b/manipulator">
        <joint name="b/elbow_joint" value="0" />
        <joint name="b/shoulder_lift_joint" value="-1.5707" />
        <joint name="b/shoulder_pan_joint" value="0" />
        <joint name="b/wrist_1_joint" value="-1.5707" />
        <joint name="b/wrist_2_joint" value="0" />
        <joint name="b/wrist_3_joint" value="0" />
    </group_state>
    <!--END EFFECTOR: Purpose: Represent information about an end effector.-->
    <end_effector name="b/moveit_ee" parent_link="b/tool0" group="b/endeffector" />
    <!--VIRTUAL JOINT: Purpose: this element defines a virtual joint between a robot link and an external frame of reference (considered fixed with respect to the robot)-->
    <virtual_joint name="b/fixed_base" type="fixed" parent_frame="world" child_link="b/base_link" />
    <!--DISABLE COLLISIONS: By default it is assumed that any link of the robot could potentially come into collision with any other link in the robot. This tag disables collision checking between a specified pair of links. -->
    <disable_collisions link1="b/base_link_inertia" link2="b/shoulder_link" reason="Adjacent" />
    <disable_collisions link1="b/base_link_inertia" link2="b/upper_arm_link" reason="Never" />
    <disable_collisions link1="b/base_link_inertia" link2="b/wrist_1_link" reason="Never" />
    <disable_collisions link1="b/forearm_link" link2="b/upper_arm_link" reason="Adjacent" />
    <disable_collisions link1="b/forearm_link" link2="b/wrist_1_link" reason="Adjacent" />
    <disable_collisions link1="b/shoulder_link" link2="b/upper_arm_link" reason="Adjacent" />
    <disable_collisions link1="b/shoulder_link" link2="b/wrist_1_link" reason="Never" />
    <disable_collisions link1="b/shoulder_link" link2="b/wrist_2_link" reason="Never" />
    <disable_collisions link1="b/wrist_1_link" link2="b/wrist_2_link" reason="Adjacent" />
    <disable_collisions link1="b/wrist_1_link" link2="b/wrist_3_link" reason="Never" />
    <disable_collisions link1="b/wrist_2_link" link2="b/wrist_3_link" reason="Adjacent" />