controller_list:
  - name: fake_ur_arm_a_controller
    joints:
      - a/shoulder_pan_joint
      - a/shoulder_lift_joint
      - a/elbow_joint
      - a/wrist_1_joint
      - a/wrist_2_joint
      - a/wrist_3_joint
  - name: fake_ur_arm_b_controller
    joints:
      - b/shoulder_pan_joint
      - b/shoulder_lift_joint
      - b/elbow_joint
      - b/wrist_1_joint
      - b/wrist_2_joint
      - b/wrist_3_joint
initial:  # Define initial robot poses.
#  - group: ur_arm_a
#    pose: home
