# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - a/shoulder_pan_joint
    - a/shoulder_lift_joint
    - a/elbow_joint
    - a/wrist_1_joint
    - a/wrist_2_joint
    - a/wrist_3_joint
    - b/shoulder_pan_joint
    - b/shoulder_lift_joint
    - b/elbow_joint
    - b/wrist_1_joint
    - b/wrist_2_joint
    - b/wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur_arm_a_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - a/shoulder_pan_joint
      - a/shoulder_lift_joint
      - a/elbow_joint
      - a/wrist_1_joint
      - a/wrist_2_joint
      - a/wrist_3_joint
  - name: ur_arm_b_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - b/shoulder_pan_joint
      - b/shoulder_lift_joint
      - b/elbow_joint
      - b/wrist_1_joint
      - b/wrist_2_joint
      - b/wrist_3_joint